USE DATABASE COS
CREATE TABLE S (S INT PRIMARY KEY)
CREATE TABLE A (A INT PRIMARY KEY  REFERENCES S (S) )

----------------------------------------------------------------

DROP DATABASE COS
CREATE DATABASE COS
USE DATABASE COS
CREATE TABLE S (S INT PRIMARY KEY)
CREATE TABLE B (B INT PRIMARY KEY)
CREATE TABLE A (  A INT PRIMARY KEY,B INT,     FOREIGN KEY S1 (A) REFERENCES S (S),     FOREIGN KEY S2 (B) REFERENCES B (B)  )
ALTER TABLE A RENAME TO AA
--CREATE TABLE C ( C INT PRIMARY KEY, FOREIGN KEY C1 (C) REFERENCES A (B))

----------------------------------------------------------------

USE DATABASE COS
DROP TABLE A

----------------------------------------------------------------

USE DATABASE COS
DROP TABLE B
DROP TABLE A
DROP TABLE B

----------------------------------------------------------------

USE DATABASE COS
DROP TABLE COSITA
CREATE TABLE cosita (c1 INT , c2 DATE , c3 INT REFERENCES A (A) , c4 CHAR(3) , PRIMARY KEY clave (c1 , c3), c5 INT CHECK (c5 > '3'), CHECK NoTanGrande (c5 < 4343433) )

----------------------------------------------------------------

USE DATABASE COS
CREATE TABLE CC (cc1 INT, CC2 DATE, PRIMARY KEY PK (CC1, CC2))
CREATE TABLE DD (DD1 DATE, DD2 INT PRIMARY KEY, DD3 FLOAT, FOREIGN KEY FK1 (DD2) REFERENCES CC ( CC1 ))

----------------------------------------------------------------

DROP DATABASE COS
CREATE DATABASE COS
USE DATABASE COS
CREATE TABLE PATIO (ID INT PRIMARY KEY)
CREATE TABLE CASA (COLOR CHAR(25))
ALTER TABLE CASA ADD COLUMN numero INT
ALTER TABLE CASA ADD COLUMN ID INT PRIMARY KEY REFERENCES PATIO (ID), ADD CHECK IDVALIDO (ID > 0)
ALTER TABLE CASA DROP COLUMN ID
ALTER TABLE CASA DROP CONSTRAINT PK000
ALTER TABLE CASA DROP COLUMN ID
ALTER TABLE CASA DROP CONSTRAINT FK000
ALTER TABLE CASA DROP COLUMN ID
ALTER TABLE CASA DROP CONSTRAINT IDVALIDO
ALTER TABLE CASA DROP COLUMN ID
----------------------------------------------------------------

